### ISSUE TITLE
Session timeout is not working

### ISSUE THREAD

**Issue by rajiv7** [ecominds/session-replication-kubernetes-redis#1]

**Comment by ecominds** [comment]
Spring session timeout is working perfectly fine. However, the duration is '1800' seconds and override is not working with the attribute 'server.servlet.session.timeout = 10m'.

Working on finding the correct one

**Comment by ecominds** [comment]
Even if the timeout is 1800, that is not working as Spring session seems working on **Cookie** with name **SESSION** and default expiry is "When the browsing session ends"
![image](https://user-images.githubusercontent.com/55941405/219070521-c081f180-61f1-4121-bbdb-67ce1f0a2a59.png)
